export const FRAMEWORKS = [
  {
    id: 'super-thinking',
    name: 'Super Thinking',
    description: '用於複雜問題、策略決策、系統分析、槓桿點、取捨、風險與誘因檢查。',
    bestFor: ['複雜問題', '策略決策', '系統分析', '風險取捨', '誘因設計', '專案預演'],
    avoidWhen: ['單純查詢事實', '已有明確公式或專業指引', '問題很小且直接行動成本低'],
    coreQuestions: [
      '真正要優化的是什麼？',
      '目前限制整體結果的瓶頸在哪裡？',
      '這個選擇的二階效果是什麼？',
      '哪些誘因會讓行為偏離目標？',
      '如果核心假設錯了，安全邊際在哪裡？',
    ],
    promptGuide: '先跑 First Pass Checklist，再依情境選模型群，最後輸出具體下一步。',
  },
  {
    id: 'thinking-fast-and-slow',
    name: 'Thinking, Fast and Slow',
    description: '用於分析直覺判斷、認知偏誤、風險框架、預測錯誤、專家直覺與不確定選擇。',
    bestFor: ['快速判斷', '預測與估期', 'base rate', 'framing effect', 'loss aversion', '專家直覺檢查'],
    avoidWhen: ['沒有判斷或決策', '已有高品質公式或演算法', '只是想把所有錯誤硬套成偏誤'],
    coreQuestions: [
      '我現在是在快速直覺，還是在慢速檢查？',
      '是否只根據眼前資訊判斷？',
      '是否有人先給出 anchor？',
      '類似案例的 base rate 是什麼？',
      '換一種 framing 後選擇會不會改變？',
    ],
    promptGuide: '先辨識 System 1/System 2 狀態，再檢查 WYSIATI、anchoring、base rate、framing 與 loss aversion。',
  },
  {
    id: 'circle-of-competence',
    name: 'Circle of Competence',
    description: '用於判斷是否該相信自己的判斷、下注、委託專家，或界定知識與無知的邊界。',
    bestFor: ['專業判斷', '高自信低證據', '進入新領域', '評估他人專家性'],
    avoidWhen: ['問題不依賴專業知識', '已有清楚可驗證資料', '只是想逃避學習或決策'],
    coreQuestions: [
      '哪些理解來自直接經驗？',
      '我能因果解釋，還是只會描述？',
      '這個領域我曾經在哪裡錯過？',
      '真正的專家會注意到什麼？',
      '我應該自己決定、補資料，還是委託？',
    ],
    promptGuide: '先標出可靠理解、淺層理解與未知區域，再決定是否行動、學習或尋求專家。',
  },
  {
    id: 'falsifiability',
    name: 'Falsifiability',
    description: '用於把主張、假設、解釋、策略、診斷或信念轉成可以被證據推翻的測試。',
    bestFor: ['假設驗證', '策略檢驗', '診斷推理', '成功標準模糊'],
    avoidWhen: ['只需描述價值偏好', '無法取得任何可觀察證據', '決策不需要驗證假設'],
    coreQuestions: [
      '什麼觀察會讓這個主張為假？',
      '在看到資料前，這個主張預測什麼？',
      '什麼結果會改變我們的看法？',
      '我們是在測試主張，還是在保護主張？',
      '停止、轉向或修正條件是什麼？',
    ],
    promptGuide: '把模糊主張改寫成可被推翻的預測，明確定義觀察、門檻與改變決策的條件。',
  },
  {
    id: 'first-principles-thinking',
    name: 'First Principles Thinking',
    description: '用於當既有假設、類比、慣例、legacy 流程或複製方案阻礙更好答案時。',
    bestFor: ['原創設計', '打破慣例', '成本或流程重設', '複製方案失效'],
    avoidWhen: ['既有最佳實務已充分驗證', '時間不足以重新設計', '限制其實是法規或安全要求'],
    coreQuestions: [
      '我們真正想達成什麼？',
      '物理、經濟、法律或心理上必須成立什麼？',
      '哪些限制是真的，哪些只是繼承來的？',
      '如果從零開始，會怎麼設計？',
      '什麼可以移除而不損害目的？',
    ],
    promptGuide: '先拆到不可再簡化的事實與限制，再從底層重組方案，不要從現有形式開始。',
  },
  {
    id: 'hanlons-razor',
    name: "Hanlon's Razor",
    description: '用於解讀有害、挫折或意外行為時，避免在檢查錯誤、混亂、誘因或限制前過度歸因惡意。',
    bestFor: ['衝突降溫', '事故檢討', '供應商或團隊失誤', '壓力下判斷意圖'],
    avoidWhen: ['已有明確惡意證據', '需要立即處理安全威脅', '用來逃避責任追究'],
    coreQuestions: [
      '有哪些非惡意解釋符合事實？',
      '對方當時有哪些資訊、誘因或限制？',
      '如果是能力不足、過載或歧義，會看到什麼？',
      '如何在不指控的情況下取得證據？',
      '無論意圖如何，什麼防護能降低再發？',
    ],
    promptGuide: '先列出非惡意解釋與可檢查證據，再分開處理影響、意圖與防再發措施。',
  },
  {
    id: 'inversion',
    name: 'Inversion',
    description: '用於避免失敗、降低風險、設計防護、debug 目標，或透過反向推理找隱藏阻礙。',
    bestFor: ['風險控管', '失敗預演', '目標 debug', '防呆設計'],
    avoidWhen: ['需要發散創意且風險很低', '已經過度防守而錯失上行', '只列風險但不做緩解'],
    coreQuestions: [
      '什麼會保證失敗？',
      '這種情況常見錯誤是什麼？',
      '什麼會讓結果不可能發生？',
      '如何提早偵測失敗？',
      '哪些失敗原因現在就能移除？',
    ],
    promptGuide: '不要只問如何成功；先反推如何失敗，再把可預防原因轉成防護與早期警訊。',
  },
  {
    id: 'map-is-not-territory',
    name: 'Map Is Not the Territory',
    description: '用於人們可能把模型、指標、儀表板、計畫、標籤、抽象或故事誤認為現實本身時。',
    bestFor: ['指標誤用', '儀表板解讀', '計畫與現實落差', '標籤或診斷替代觀察'],
    avoidWhen: ['代表物與現實剛被交叉驗證', '只是在討論命名約定', '沒有可接觸的現實樣本'],
    coreQuestions: [
      '這張 map 代表哪個真實事物？',
      '哪些細節被簡化或隱藏？',
      '哪些誘因塑造了這個表示？',
      '哪裡可以直接抽樣現實？',
      '什麼會證明這張 map 過時或誤導？',
    ],
    promptGuide: '把任何表示都當成部分真相；檢查它顯示什麼、隱藏什麼，以及現實是否已改變。',
  },
  {
    id: 'necessity-and-sufficiency',
    name: 'Necessity and Sufficiency',
    description: '用於釐清某因素是必要、充分、只是有幫助，還是被誤認為完整原因。',
    bestFor: ['需求釐清', '因果條件', '成功條件', '多因素問題'],
    avoidWhen: ['只需排序偏好', '因素間關係已由實驗明確確認', '問題不是條件或原因判斷'],
    coreQuestions: [
      '這個因素對結果是必要的嗎？',
      '只要有這個因素，結果就會穩定發生嗎？',
      '還必須同時成立什麼？',
      '沒有這個因素，結果可能發生嗎？',
      '我們是在描述單一材料，還是完整配方？',
    ],
    promptGuide: '分開標示必要條件、充分條件、輔助因素與完整條件組合，避免把一個因素當成全部原因。',
  },
  {
    id: 'occams-razor',
    name: "Occam's Razor",
    description: '用於比較多個解釋時，較簡單的解釋可能用更少假設就符合證據。',
    bestFor: ['解釋比較', 'debug 推理', '降低猜測', '避免保護偏好故事'],
    avoidWhen: ['已有證據支持複雜原因', '簡化會忽略罕見但重大風險', '用簡單當藉口停止調查'],
    coreQuestions: [
      '哪個解釋需要最少假設？',
      '哪些假設承擔最多解釋重量？',
      '什麼證據會支持更複雜的解釋？',
      '我們是在解釋事實，還是在保護故事？',
      '第一個簡單檢查是什麼？',
    ],
    promptGuide: '先選能解釋證據且假設最少的解釋，但保留被證據迫使增加複雜度的空間。',
  },
  {
    id: 'probabilistic-thinking',
    name: 'Probabilistic Thinking',
    description: '用於結果不確定，決策需要機率、範圍、base rate、expected value、信心水準或風險取捨時。',
    bestFor: ['預測', '風險決策', '投資或上線判斷', '不完整證據'],
    avoidWhen: ['結果已確定且只需執行', '沒有任何可用 base rate 或更新證據', '使用機率掩飾價值選擇'],
    coreQuestions: [
      '可能結果與機率範圍是什麼？',
      '類似案例的 base rate 是什麼？',
      '哪些證據應該更新機率？',
      'expected value 與 downside risk 是什麼？',
      '信心多高，什麼會改變信心？',
    ],
    promptGuide: '用範圍、base rate、期望值與信心水準取代確定語氣，並明確列出更新條件。',
  },
  {
    id: 'second-order-thinking',
    name: 'Second-Order Thinking',
    description: '用於決策可能有延遲效果、副作用、誘因改變、回饋迴路或超出立即結果的後果時。',
    bestFor: ['政策或產品決策', '誘因設計', '系統副作用', '長短期取捨'],
    avoidWhen: ['決策低風險且可快速逆轉', '過度分析會延誤必要行動', '第一層問題尚未釐清'],
    coreQuestions: [
      '立即效果是什麼？',
      '人們適應後會發生什麼？',
      '誰會因這個決策改變行為？',
      '可能出現什麼 feedback loop？',
      '一週、一年、放大後會如何？',
    ],
    promptGuide: '往下一層再下一層追問後果，尤其檢查誘因改變、適應行為與規模化副作用。',
  },
  {
    id: 'thought-experiment',
    name: 'Thought Experiment',
    description: '用於在不確定、風險、限制或倫理複雜下，先用想像情境安全測試想法。',
    bestFor: ['高成本測試', '極端情境推理', '隱藏假設', '比較未來方案'],
    avoidWhen: ['可以低成本實測', '把想像誤當證據', '情境設定已偷渡想要的答案'],
    coreQuestions: [
      '什麼情境能隔離關鍵變數？',
      '把限制加倍、減半、移除或反轉會如何？',
      '如果所有人都複製這個行動會怎樣？',
      '如果相反假設為真，我們會怎麼做？',
      '什麼結果會讓我們意外？',
    ],
    promptGuide: '建立有紀律的想像情境來隔離變數、測試邏輯與後果，之後仍要回到現實驗證。',
  },
  {
    id: 'causation-vs-correlation',
    name: 'Causation vs Correlation',
    description: '用於兩個變數一起變動，且有人可能從圖表、軼事、實驗或觀察資料推論因果時。',
    bestFor: ['資料解讀', '因果推論', '儀表板分析', '找真正槓桿'],
    avoidWhen: ['已有良好隨機實驗證據', '只需描述相關性而非決策', '沒有足夠資料檢查替代解釋'],
    coreQuestions: [
      '哪個先發生？',
      '連接因與果的機制是什麼？',
      '什麼第三因素可能同時解釋兩者？',
      '是否有選擇偏誤或反向因果？',
      '能否做實驗、自然實驗或配對比較？',
    ],
    promptGuide: '不要把共變當因果；檢查時間順序、機制、混淆因子、反向因果與可行測試。',
  },
];
